const songs = [
  {
    fileName: '01-TheSmiths-TheQueenIsDead',
    displayName: 'The Queen Is Dead(Take Me Back To Dear Old Blightly Medley)',
    artist: 'The Smiths',
    album: 'The Queen Is Dead',
    albumCover: 'the_queen_is_dead',
  },
  {
    fileName: '02-The Smiths-FranklyMrShankly',
    displayName: 'Frankly, Mr. Shankly',
    artist: 'The Smiths',
    album: 'The Queen Is Dead',
    albumCover: 'the_queen_is_dead',
  },
  {
    fileName: '03-TheSmiths-IKnowItsOver',
    displayName: "I Know It's Over",
    artist: 'The Smiths',
    album: 'The Queen Is Dead',
    albumCover: 'the_queen_is_dead',
  },
  {
    fileName: '04-TheSmiths-NeverHadNoOneEver',
    displayName: 'Never Had No One Ever',
    artist: 'The Smiths',
    album: 'The Queen Is Dead',
    albumCover: 'the_queen_is_dead',
  },
  {
    fileName: '05-TheSmiths-CemetryGates',
    displayName: 'Cemetry Gates',
    artist: 'The Smiths',
    album: 'The Queen Is Dead',
    albumCover: 'queen_is_dead2',
  },
  {
    fileName: '06-TheSmiths-BigmouthStrikesAgain',
    displayName: 'Bigmouth Strikes Again',
    artist: 'The Smiths',
    album: 'The Queen Is Dead',
    albumCover: 'queen_is_dead2',
  },
  {
    fileName: '07-TheSmiths-TheBoyWithTheThornInHisSide',
    displayName: 'The Boy With The Torn In His Side',
    artist: 'The Smiths',
    album: 'The Queen Is Dead',
    albumCover: 'queen_is_dead2',
  },
  {
    fileName: '08-TheSmiths-VicarInATutu',
    displayName: 'Vicar In A Tutu',
    artist: 'The Smiths',
    album: 'The Queen Is Dead',
    albumCover: 'queen_is_dead2',
  },
  {
    fileName: '09-TheSmiths-ThereIsALightThatNeverGoesOut',
    displayName: 'There Is A Light That Never Goes Out',
    artist: 'The Smiths',
    album: 'The Queen Is Dead',
    albumCover: 'queen_is_dead2',
  },
  {
    fileName: '10-TheSmiths-SomeGirlsAreBiggerThanOthers',
    displayName: 'Some Girls Are Bigger Than Others',
    artist: 'The Smiths',
    album: 'The Queen Is Dead',
    albumCover: 'queen_is_dead2',
  },
  {
    fileName: '01 - Is It Really So Strange',
    displayName: 'Is It Really So Strange',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '02 - Sheila Take A Bow',
    displayName: 'Sheila Take A Bow',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '03 - Shoplifters Of The World Unite',
    displayName: 'Shoplifters Of The World Unite',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '04 - Sweet And Tender Hooligan',
    displayName: 'Sweet And Tender Hooligan',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '05 - Half A Person',
    displayName: 'Half A Person',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '06 - London',
    displayName: 'London',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '07 - Panic',
    displayName: 'Panic',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '08 - Girl Afraid',
    displayName: 'Girl Afraid',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: `09 - Shakespeare's Sister`,
    displayName: `Shakespeare's Sister`,
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '10 - William, It Was Really Nothing',
    displayName: 'William, It Was Really Nothing',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: `11 - You Just Haven't Earned It Yet, Baby`,
    displayName: `You Just Haven't Earned It Yet, Baby`,
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: `12 - Heaven Knows I'm Miserable Now`,
    displayName: `Heaven Knows I'm Miserable Now`,
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '13 - Ask',
    displayName: 'Ask',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '14 - Golden Lights',
    displayName: 'Golden Lights',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '15 - Oscillate Wildly',
    displayName: 'Oscillate Wildly',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '16 - These Things Take Time',
    displayName: 'These Things Take Time',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '17 - Rubber Ring',
    displayName: 'Rubber Ring',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '18 - Back To The Old House',
    displayName: 'Back To The Old House',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '19 - Hand In Glove',
    displayName: 'Hand In Glove',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '20 - Stretch Out And Wait',
    displayName: 'Stretch Out And Wait',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '21 - Please Please Please Let Me Get What I Want',
    displayName: 'Please Please Please Let Me Get What I Want',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '22 - This Night Has Opened My Eyes',
    displayName: 'This Night Has Opened My Eyes',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '23 - Unlovable',
    displayName: 'Unlovable',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '24 - Asleep',
    displayName: 'Asleep',
    artist: 'The Smiths',
    album: 'Louder Than Bombs',
    albumCover: 'louder_than_bombs',
  },
  {
    fileName: '01 - The Headmaster Ritual',
    displayName: 'The Headmaster Ritual',
    artist: 'The Smiths',
    album: 'Meat is Murder',
    albumCover: 'the_smiths_meat_is_murder',
  },
  {
    fileName: '02 - Rusholme Ruffians',
    displayName: 'Rusholme Ruffians',
    artist: 'The Smiths',
    album: 'Meat is Murder',
    albumCover: 'the_smiths_meat_is_murder',
  },
  {
    fileName: `03 - I Want the One I Can't Have`,
    displayName: `I Want the One I Can't Have`,
    artist: 'The Smiths',
    album: 'Meat is Murder',
    albumCover: 'the_smiths_meat_is_murder',
  },
  {
    fileName: `04 - The Joke Isn't Funny Anymore`,
    displayName: `The Joke Isn't Funny Anymore`,
    artist: 'The Smiths',
    album: 'Meat is Murder',
    albumCover: 'the_smiths_meat_is_murder',
  },
  {
    fileName: `05 - How Soon Is Now`,
    displayName: `How Soon Is Now`,
    artist: 'The Smiths',
    album: 'Meat is Murder',
    albumCover: 'the_smiths_meat_is_murder',
  },
  {
    fileName: '06 - Nowhere Fast',
    displayName: 'Nowhere Fast',
    artist: 'The Smiths',
    album: 'Meat is Murder',
    albumCover: 'meat_is_murder',
  },
  {
    fileName: '07 - Well I Wonder',
    displayName: 'Well I Wonder',
    artist: 'The Smiths',
    album: 'Meat is Murder',
    albumCover: 'meat_is_murder',
  },
  {
    fileName: '08 - Barbarism Begins at Home',
    displayName: 'Barbarism Begins at Home',
    artist: 'The Smiths',
    album: 'Meat is Murder',
    albumCover: 'meat_is_murder',
  },
  {
    fileName: '09 - Meat is Murder',
    displayName: 'Meat is Murder',
    artist: 'The Smiths',
    album: 'Meat is Murder',
    albumCover: 'meat_is_murder',
  },
  {
    fileName: '01 - A Rush and a Push and the Land Is Ours',
    displayName: 'A Rush and a Push and the Land Is Ours',
    artist: 'The Smiths',
    album: 'Strangeways, Here We Come',
    albumCover: 'strangeways_here_we_come',
  },
  {
    fileName: `02 - I Started Something I Couldn't Finish`,
    displayName: `I Started Something I Couldn't Finish`,
    artist: 'The Smiths',
    album: 'Strangeways, Here We Come',
    albumCover: 'strangeways_here_we_come',
  },
  {
    fileName: '03 - Death of a Disco Dancer',
    displayName: 'Death of a Disco Dancer',
    artist: 'The Smiths',
    album: 'Strangeways, Here We Come',
    albumCover: 'strangeways_here_we_come',
  },
  {
    fileName: '04 - Girlfriend in a Coma',
    displayName: 'Girlfriend in a Coma',
    artist: 'The Smiths',
    album: 'Strangeways, Here We Come',
    albumCover: 'strangeways_here_we_come',
  },
  {
    fileName: `05 - Stop Me If You Think You've Heard This One Before`,
    displayName: `Stop Me If You Think You've Heard This One Before`,
    artist: 'The Smiths',
    album: 'Strangeways, Here We Come',
    albumCover: 'strangeways_here_we_come2',
  },
  {
    fileName: '06 - Last Night I Dreamt That Somebody Loved Me',
    displayName: 'Last Night I Dreamt That Somebody Loved Me',
    artist: 'The Smiths',
    album: 'Strangeways, Here We Come',
    albumCover: 'strangeways_here_we_come2',
  },
  {
    fileName: '07 - Unhappy Birthday',
    displayName: 'Unhappy Birthday',
    artist: 'The Smiths',
    album: 'Strangeways, Here We Come',
    albumCover: 'strangeways_here_we_come2',
  },
  {
    fileName: '08 - Paint a Vulgar Picture',
    displayName: 'Paint a Vulgar Picture',
    artist: 'The Smiths',
    album: 'Strangeways, Here We Come',
    albumCover: 'strangeways_here_we_come2',
  },
  {
    fileName: `09 - Death at One's Elbow`,
    displayName: `Death at One's Elbow`,
    artist: 'The Smiths',
    album: 'Strangeways, Here We Come',
    albumCover: 'strangeways_here_we_come2',
  },
  {
    fileName: `10 - I Won't Share You`,
    displayName: `I Won't Share You`,
    artist: 'The Smiths',
    album: 'Strangeways, Here We Come',
    albumCover: 'strangeways_here_we_come2',
  },
];

module.exports = { songs };
